version: '3.8'

services:
  redis-cluster:
    image: grokzen/redis-cluster:6.2.14
    ports:
      - "7100-7105:7100-7105"
    environment:
      - "INITIAL_PORT=7100"
      - "REDIS_CLUSTER_IP=0.0.0.0"
      - "IP=0.0.0.0"
      - "BIND_ADDRESS=0.0.0.0"
    restart: "no"
